# fly.toml app configuration file generated for api-users-no-waste on 2025-09-03T18:08:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-users-no-waste'
primary_region = 'fra'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 5003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
