module.exports = async function seedItems(prisma) {
  const items = [
    { name: "Whole Wheat Bread (500g)", type: "bread", price: 2.5 },
    { name: "White Bread (500g)", type: "bread", price: 1.8 },
    { name: "Sourdough Bread (400g)", type: "bread", price: 3.2 },
    { name: "Ciabatta Bread (500g)", type: "bread", price: 2.9 },
    { name: "Baguette (300g)", type: "bread", price: 1.7 },
    { name: "Rye Bread (500g)", type: "bread", price: 3.0 },
    { name: "Multigrain Bread (500g)", type: "bread", price: 2.8 },
    { name: "Pita Bread (400g)", type: "bread", price: 2.4 },
    { name: "English Muffins (300g)", type: "bread", price: 2.3 },
    { name: "Pumpernickel Bread (500g)", type: "bread", price: 3.3 },
    { name: "Chicken Breast (1kg)", type: "meat", price: 8.0 },
    { name: "Pork Tenderloin (1kg)", type: "meat", price: 7.5 },
    { name: "Beef Steak (1kg)", type: "meat", price: 12.0 },
    { name: "Ground Beef (1kg)", type: "meat", price: 9.0 },
    { name: "Lamb Chops (1kg)", type: "meat", price: 15.0 },
    { name: "Turkey Breast (1kg)", type: "meat", price: 8.5 },
    { name: "Chicken Thighs (1kg)", type: "meat", price: 7.0 },
    { name: "Beef Ribs (1kg)", type: "meat", price: 14.0 },
    { name: "Veal (1kg)", type: "meat", price: 16.0 },
    { name: "Salmon (1kg)", type: "fish", price: 15.0 },
    { name: "Tuna (1kg)", type: "fish", price: 18.0 },
    { name: "Cod (1kg)", type: "fish", price: 14.0 },
    { name: "Trout (1kg)", type: "fish", price: 16.5 },
    { name: "Halibut (1kg)", type: "fish", price: 20.0 },
    { name: "Mackerel (1kg)", type: "fish", price: 12.0 },
    { name: "Shrimp (500g)", type: "fish", price: 22.0 },
    { name: "Squid (500g)", type: "fish", price: 18.0 },
    { name: "Sardines (1kg)", type: "fish", price: 10.0 },
    { name: "Cheddar Cheese (500g)", type: "cheese", price: 10.0 },
    { name: "Mozzarella Cheese (500g)", type: "cheese", price: 8.5 },
    { name: "Parmesan Cheese (500g)", type: "cheese", price: 18.0 },
    { name: "Gouda Cheese (500g)", type: "cheese", price: 12.0 },
    { name: "Brie Cheese (500g)", type: "cheese", price: 16.0 },
    { name: "Swiss Cheese (500g)", type: "cheese", price: 14.0 },
    { name: "Feta Cheese (500g)", type: "cheese", price: 9.0 },
    { name: "Ricotta Cheese (500g)", type: "cheese", price: 7.5 },
    { name: "Cream Cheese (500g)", type: "cheese", price: 5.0 },
    { name: "Cottage Cheese (500g)", type: "cheese", price: 6.5 },
    { name: "Carrots (1kg)", type: "vegetables", price: 2.0 },
    { name: "Broccoli (1kg)", type: "vegetables", price: 3.0 },
    { name: "Spinach (500g)", type: "vegetables", price: 2.5 },
    { name: "Tomatoes (1kg)", type: "vegetables", price: 3.5 },
    { name: "Potatoes (1kg)", type: "vegetables", price: 2.0 },
    { name: "Lettuce (300g)", type: "vegetables", price: 2.5 },
    { name: "Onions (1kg)", type: "vegetables", price: 1.5 },
    { name: "Garlic (200g)", type: "vegetables", price: 3.0 },
    { name: "Peppers (1kg)", type: "vegetables", price: 4.0 },
    { name: "Cabbage (1kg)", type: "vegetables", price: 2.8 },
    { name: "Canned Beans (400g)", type: "canned-vegetables", price: 1.2 },
    { name: "Canned Corn (400g)", type: "canned-vegetables", price: 1.0 },
    { name: "Canned Peas (400g)", type: "canned-vegetables", price: 1.5 },
    { name: "Canned Tomatoes (400g)", type: "canned-vegetables", price: 1.8 },
    { name: "Canned Mushrooms (400g)", type: "canned-vegetables", price: 2.0 },
    { name: "Canned Spinach (400g)", type: "canned-vegetables", price: 1.9 },
    { name: "Canned Carrots (400g)", type: "canned-vegetables", price: 1.7 },
    {
      name: "Canned Mixed Vegetables (400g)",
      type: "canned-vegetables",
      price: 2.3,
    },
    { name: "Canned Sweet Corn (400g)", type: "canned-vegetables", price: 2.1 },
    { name: "Canned Potato (400g)", type: "canned-vegetables", price: 2.2 },
    {
      name: "Canned Peas and Carrots (400g)",
      type: "canned-vegetables",
      price: 2.0,
    },
    { name: "Canned Tuna (200g)", type: "canned-fish", price: 3.0 },
    { name: "Canned Salmon (200g)", type: "canned-fish", price: 4.5 },
    { name: "Canned Sardines (200g)", type: "canned-fish", price: 2.5 },
    { name: "Canned Anchovies (200g)", type: "canned-fish", price: 2.8 },
    { name: "Canned Mackerel (200g)", type: "canned-fish", price: 3.5 },
    { name: "Canned Chicken (300g)", type: "canned-meat", price: 3.0 },
    { name: "Canned Pork (300g)", type: "canned-meat", price: 3.2 },
    { name: "Canned Beef (300g)", type: "canned-meat", price: 3.5 },
    { name: "Canned Turkey (300g)", type: "canned-meat", price: 3.8 },
    { name: "Canned Lamb (300g)", type: "canned-meat", price: 4.0 },
    { name: "Canned Cheese (200g)", type: "canned-cheese", price: 5.0 },
    { name: "Canned Cheddar (200g)", type: "canned-cheese", price: 6.0 },
    { name: "Canned Mozzarella (200g)", type: "canned-cheese", price: 5.5 },
    { name: "Canned Brie (200g)", type: "canned-cheese", price: 7.0 },
    { name: "Canned Swiss Cheese (200g)", type: "canned-cheese", price: 6.5 },
    { name: "Canned White Bread (500g)", type: "canned-bread", price: 3.8 },
    { name: "Canned Sourdough Bread (500g)", type: "canned-bread", price: 4.0 },
    { name: "Canned Rye Bread (500g)", type: "canned-bread", price: 4.2 },
    {
      name: "Canned Multigrain Bread (500g)",
      type: "canned-bread",
      price: 3.9,
    },
    { name: "Canned Ciabatta Bread (500g)", type: "canned-bread", price: 4.1 },
    { name: "Canned Baguette (300g)", type: "canned-bread", price: 2.5 },
    { name: "Canned English Muffins (300g)", type: "canned-bread", price: 2.7 },
    { name: "Canned Pita Bread (400g)", type: "canned-bread", price: 3.0 },
    {
      name: "Canned Pumpernickel Bread (500g)",
      type: "canned-bread",
      price: 4.3,
    },
    { name: "Apples (1kg)", type: "other", price: 3.0 },
    { name: "Bananas (1kg)", type: "other", price: 2.0 },
    { name: "Oranges (1kg)", type: "other", price: 2.5 },
    { name: "Pineapple (1kg)", type: "other", price: 5.0 },
    { name: "Grapes (1kg)", type: "other", price: 4.0 },
    { name: "Strawberries (500g)", type: "other", price: 6.0 },
    { name: "Blueberries (200g)", type: "other", price: 8.0 },
    { name: "Lemon (500g)", type: "other", price: 2.8 },
    { name: "Yogurt (1L)", type: "other", price: 2.2 },
    { name: "Milk (1L)", type: "other", price: 1.0 },
    { name: "Canned Mixed Fruit (400g)", type: "canned-other", price: 2.5 },
    { name: "Canned Pineapple (400g)", type: "canned-other", price: 3.0 },
    { name: "Canned Peach (400g)", type: "canned-other", price: 2.7 },
    { name: "Canned Apple (400g)", type: "canned-other", price: 2.6 },
    { name: "Canned Orange (400g)", type: "canned-other", price: 3.2 },
    { name: "Canned Lemon (400g)", type: "canned-other", price: 3.5 },
    { name: "Canned Tomatoes (400g)", type: "canned-vegetables", price: 1.8 },
    { name: "Canned Mushrooms (400g)", type: "canned-vegetables", price: 2.0 },
    { name: "Canned Spinach (400g)", type: "canned-vegetables", price: 1.9 },
    { name: "Canned Carrots (400g)", type: "canned-vegetables", price: 1.7 },
    {
      name: "Canned Mixed Vegetables (400g)",
      type: "canned-vegetables",
      price: 2.3,
    },
    { name: "Canned Sweet Corn (400g)", type: "canned-vegetables", price: 2.1 },
    { name: "Canned Potato (400g)", type: "canned-vegetables", price: 2.2 },
    {
      name: "Canned Peas and Carrots (400g)",
      type: "canned-vegetables",
      price: 2.0,
    },
    { name: "Canned Peas (400g)", type: "canned-vegetables", price: 1.5 },
  ];
  
  for (const item of items) {
    const inventoryId = Math.floor(Math.random() * 3) + 1;
    const productionDate = new Date();
    const expirationDate = new Date(
      productionDate.getTime() +
        Math.floor(Math.random() * 30 + 5) * 24 * 60 * 60 * 1000
    );

    const createdByUserId = 35;

    await prisma.item.create({
      data: {
        inventoryId,
        name: item.name,
        type: item.type,
        productionDate,
        expirationDate,
        price: item.price,
        createdByUserId,
      },
    });
  }
};
